### ISSUE TITLE
cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: noneClassicRegistry

### ISSUE THREAD

**Issue by Tsyklop** [TinyModularThings/IC2-Nei-Plugin#2]
http://pastebin.com/GFCmPi4U

IC2 Nei Plugin Version 1.0.9
IC2 Wrench Plugin Version 1.0.1

**Comment by Speiger** [comment]
Yeah the Wrench plugin is not updated to the new Classic API. Just delete the API from IC2 out of the wrench plugin and everything should be fine^^

**Comment by Speiger** [comment]
Ill update the Wrench handler this week too.

**Comment by Speiger** [comment]
@Tsyklop uploading the Updated version of the Wrench plugin
