### ISSUE TITLE
API Inclusion

### ISSUE THREAD

**Issue by Chocohead** [TinyModularThings/IC2-Nei-Plugin#3]
You include bits of the classic API, enough for Nuclear Control to be confused into classic being loaded from this line: https://github.com/xbony2/Nuclear-Control/blob/master/src/main/java/shedar/mods/ic2/nuclearcontrol/crossmod/ic2classic/CrossIndustrialCraft2Classic.java#L15

**Comment by Speiger** [comment]
true at that point i did not have the second modid... it came after that...

**Comment by Speiger** [comment]
https://github.com/xbony2/Nuclear-Control/pull/134
Wait for NC
