### ISSUE TITLE
Source Provisions

### ISSUE THREAD

**Issue by draknyte1** [TinyModularThings/IC2-Nei-Plugin#5]
Hey Speiger!

Since it looks like you're no longer maintaining this mod, would you be able to upload the source so that better IC2Exp compat and other fixes could be applied?

Thanks,
Alk.

**Comment by Speiger** [comment]
@draknyte1 @bedrill64 @Anarack @bartimaeusnek report the issues instead of assuming things that are not true.
I am glad to fix these issues but open source will not be an option and forks of alk will be removed if nessesary, since i told him that he has no permission to steal the project.

**Comment by Speiger** [comment]
Issue got created, now fixing it. @draknyte1 is banned just to provide that info.

**Comment by DietmarKracht** [comment]
#UnbanAlk

**Comment by TeaWithLemonSerDav74** [comment]
#UnbanAlk

**Comment by Speiger** [comment]
For putting just some context into this: 
Alk was not interested in getting the fix in, he was just interested in getting the source. And if i didnt provide the source he would just take it and release the mod on its own. He will deny the fact but here is some clear indications.

![discord_2019-02-26_16-11-32](https://user-images.githubusercontent.com/2556269/53423426-a169c880-39e1-11e9-9f68-f073eeb556c0.png)
![discord_2019-02-26_16-12-57](https://user-images.githubusercontent.com/2556269/53423475-b2b2d500-39e1-11e9-833d-665e2d45df12.png)

It was his choice to get banned.
