### ISSUE TITLE
Crash while loading mod ingame. [GTNH]

### ISSUE THREAD

**Issue by bedrill64** [TinyModularThings/IC2-Nei-Plugin#6]
Adding crash log file for you to analyze, happend after swapping old plugin file [IC2.Nei.Plugin.Version.1.1.0] with recent one you updated[IC2+Nei+Plugin+Version+1.7.10-1.2].
[crash-2019-02-26_18.37.49-client.txt](https://github.com/TinyModularThings/IC2-Nei-Plugin/files/2906784/crash-2019-02-26_18.37.49-client.txt)

**Comment by Revemohl** [comment]
I'm getting a java.lang.NoClassDefFoundError on my own pack as well, but it's pointing at ic2/core/block/crop/IC2Crops at world load and it's not generating a crash log.

**Comment by Speiger** [comment]
@bedrill64 @Revemohl yeah i derped hard there. Basically while porting stuff i accedently added a IC2C dependency to it and when shipping the tool i removed the required api files that it needs to actually run with IC2Exp. The issue has been fixed and was submitted to curse which should come out any moment after this message was posted.
