### ISSUE TITLE
Another plugin related crash.

### ISSUE THREAD

**Issue by bedrill64** [TinyModularThings/IC2-Nei-Plugin#8]
In this case I have no idea what caused crash, was doing stuff totally not related with crops, all I can read that is related with your plugin.
[crash-2019-02-28_01.52.50-client.txt](https://github.com/TinyModularThings/IC2-Nei-Plugin/files/2912903/crash-2019-02-28_01.52.50-client.txt)

Edit, crashes while trying to type c in nei, so it may be hotkey related bug as ctrl+c is shortcut for cropnalazer breed mode.
[crash-2019-02-28_03.28.47-client.txt](https://github.com/TinyModularThings/IC2-Nei-Plugin/files/2913145/crash-2019-02-28_03.28.47-client.txt)

**Comment by Speiger** [comment]
Yeah this was an oversight from me. I will patch this when the other issue is solved too.
